# fly.toml app configuration file generated for server-finance-dashboard on 2023-12-10T18:36:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "server-finance-dashboard"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
